#!/usr/bin/env bash

current_chip=$(screen -ls | grep .chip | head -n 1 | awk '{$1=$1;print}' | cut -d' ' -f1)

if [[ -n "$current_chip" ]]; then
	screen -r $current_chip
else
	screen -S chip $(cd /dev/ && ls | grep tty.usbmodem | head -n 1 | xargs readlink -f) 115200
fi

